apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: plant-simulator-monitoring
  labels:
    name: {{ .Values.prometheusService.name }}
    component: {{ .Values.prometheusService.component }}
    part-of: {{ .Values.prometheusService.name }}
    managed-by: helm
    instance: {{ .Values.prometheusService.name }}
    version: {{ .Values.app.version }} # TODO: Better use the Prometheus version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-simulator-prometheus
  template:
    metadata:
      labels:
        name: plant-simulator-prometheus
    spec:
      securityContext:
        runAsUser: {{  .Values.app.securityContext.runAsUser }}
        runAsGroup: {{  .Values.app.securityContext.runAsGroup }}
        fsGroup: {{  .Values.app.securityContext.fsGroup }}
        runAsNonRoot: {{  .Values.app.securityContext.runAsNonRoot }}
      containers:
        - name: prometheus
          image: {{ .Values.prometheusService.image.repository}}:{{ .Values.prometheusService.image.tag}}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          emptyDir: {}