apiVersion: v2
name: plant-simulator-deployment
version: 1.0.0
description: Helm charts for plant-simulator project
keywords:
  - plant-simulator
  - microservice
home: https://github.com/joesan/plant-simulator
maintainers:
  - name: Joesan
    email: https://github.com/joesan
    url: https://www.bigelectrons.com
