# Default values for plant-simulator-deployment

replicaCount: 1

app:
  version: 636 # This should be injected by the Travis CI build of the plant-simulator project
  namespace: plant-simulator-ns

plantSimulatorService:
  deployment:
    image: docker.io/joesan/plant-simulator
    tag: 636
    containerPort: 9000
    pullPolicy: IfNotPresent
  service:
    namespace: plant-simulator
    name: plant-simulator-service
    type: ClusterIP
    port: 9000
    portName: plant-simulator-service-port
    targetPort: 9000
  ingress:
    host: ????
