apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/component: {{ .Values.plantSimulatorService.component }}
    app.kubernetes.io/part-of: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/instance: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Values.app.version }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      securityContext:
        runAsUser: {{  .Values.app.securityContext.runAsUser }}
        runAsGroup: {{  .Values.app.securityContext.runAsGroup }}
        fsGroup: {{  .Values.app.securityContext.fsGroup }}
        runAsNonRoot: {{  .Values.app.securityContext.runAsNonRoot }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.plantSimulatorService.image.repository }}:{{ .Values.plantSimulatorService.image.tag }}
          ports:
            - containerPort: {{ .Values.plantSimulatorService.ports.containerPort }} # Get this value from ConfigMap

