apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: plant-simulator-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /metrics
    prometheus.io/port:   '80'
spec:
  rules:
    - host: grafana.local
      http:
        paths: 
          - backend: 
              serviceName: plant-simulator-grafana
              servicePort: 8080

    - host: prometheus.local
      http:
        paths: 
          - backend: 
              serviceName: plant-simulator-prometheus
              servicePort: 8080 

    - host: plant-simulator.local
      http:
        paths:
          - backend: 
              serviceName: plant-simulator-service
              servicePort: 9000 
