apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.plantSimulatorService.service.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    name: {{ .Values.plantSimulatorService.service.name }}
spec:
  type: {{ .Values.plantSimulatorService.service.type }}
  ports:
    - port: {{ .Values.plantSimulatorService.service.port }}
      targetPort: {{ .Values.plantSimulatorService.service.targetPort }}
      protocol: TCP
      name: {{ .Values.plantSimulatorService.service.portName }}
  selector:
    app: {{ .Values.app.name }}