apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-simulator
  namespace: plant-simulator-ns
spec:
  selector:
    matchLabels:
      app: plant-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: plant-simulator
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9000 # Get this value from ConfigMap
