apiVersion: v1
kind: Service
metadata:
  name: plant-simulator-service
  namespace: {{ .Values.app.namespace }}
  labels:
    name: {{ .Values.plantSimulatorService.service.name }}
spec:
  ports:
    - port: {{ .Values.plantSimulatorService.service.port }}
      targetPort: {{ .Values.plantSimulatorService.service.targetPort }}
      protocol: TCP
      name: {{ .Values.plantSimulatorService.service.portName }}
  selector:
    app: plant-simulator