apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-simulator
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    matchLabels:
      app: plant-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: plant-simulator
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.plantSimulatorService.deployment.image }}:{{ .Values.plantSimulatorService.deployment.tag }}"
          ports:
            - containerPort: {{ .Values.plantSimulatorService.deployment.containerPort }} # Get this value from ConfigMap
