apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: plant-simulator-kustomization
resources:
  # 0. Get the namespaces first
  #- application/plant-simulator-namespace.yaml
  - monitoring/plant-simulator-monitoring-namespace.yaml

  # 1. Set up monitoring services (prometheus)
  #- monitoring/prometheus/prometheus-roles.yaml
  - monitoring/prometheus/config-map.yaml
  - monitoring/prometheus/prometheus-roles.yaml
  - monitoring/prometheus/prometheus-deployment.yaml
  - monitoring/prometheus/prometheus-service.yaml

  # 2. Set up monitoring services (grafana)
  - monitoring/grafana/grafana-deployment.yaml
  - monitoring/grafana/grafana-service.yaml

  # 3. Set up Ingress service
  - application/plant-simulator-ingress-service.yaml

  # 4. Set up the application services (backend)
  - application/plant-simulator-namespace.yaml
  - application/plant-simulator-service.yaml
  - application/plant-simulator-deployment.yaml

  # 5. Set up the application services (frontend) [[ TODO ]]
