# Default values for plant-simulator-deployment

replicaCount: 1
app:
  version: v1.0.16 # This should be injected by the Travis CI build of the plant-simulator project CI / CD pipeline
  name: plant-simulator
  namespace: plant-simulator-ns
  ## Deployment Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    runAsNonRoot: true
grafanaService:
  component: monitoring
  name: plant-simulator-grafana
  port: 8080
prometheusService:
  component: monitoring
  name: plant-simulator-prometheus
  port: 8080
  image:
    repository: prom/prometheus
    tag: v2.23.0
plantSimulatorService:
  component: server
  image: # Docker tag will be the app.version
    repository: docker.io/joesan/plant-simulator
    pullPolicy: IfNotPresent
  ports:
    containerPort: 8080
  service:
    name: plant-simulator-service
    type: ClusterIP
    port: 9000
    portName: plant-simulator-service-port
    targetPort: 9000
  ingress:
    host: ????
