---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-{{ .Values.app.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/component: {{ .Values.plantSimulatorService.component }}
    app.kubernetes.io/part-of: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/instance: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Values.app.version }}
    fluxPatchFile: patchFile
  annotations:
    fluxcd.io/automated: "true"
  namespace: {{ .Values.app.namespace }}
