---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fluxPatchFile: patchFile
  annotations:
    fluxcd.io/automated: "true"
  name: plant-simulator-dev
  namespace: {{ .Values.app.namespace }}