---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fluxPatchFile: devPatchFile
  annotations:
    fluxcd.io/automated: "true"
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}