---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fluxPatchFile: patchFile
  annotations:
    fluxcd.io/automated: "true"
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.app.name }}