---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-{{ .Values.app.name }}
  labels:
    fluxPatchFile: patchFile
  annotations:
    flux.weave.works/locked: "true"
    flux.weave.works/locked_msg: Lock deployment in production
    flux.weave.works/locked_user: Joesan <github.com/joesan>
  namespace: {{ .Values.app.namespace }}