apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: plant-simulator-monitoring
  labels:
    name: {{ .Values.grafanaService.name }}
    component: {{ .Values.grafanaService.component }}
    part-of: {{ .Values.grafanaService.name }}
    managed-by: helm
    instance: {{ .Values.grafanaService.name }}
    version: {{ .Values.app.version }} # TODO: Better use the Grafana version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-simulator-grafana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: plant-simulator-grafana
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
      - image: grafana/grafana:6.6.2
        imagePullPolicy: IfNotPresent
        name: plant-simulator-grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data