apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-simulator
  namespace: plant-simulator-ns
spec:
  selector:
    matchLabels:
      app: plant-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: plant-simulator
    spec:
      containers:
        - name: plant-simulator
          image: 'docker.io/joesan/plant-simulator:517'
          ports:
            - containerPort: 9000