# This is a basic workflow to help you get started with Actions

name: ValidateKubernetesYAML

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ feature-ci-tests ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Kubeval
        uses: stefanprodan/kube-tools@v1.5.0
        with:
          kubectl: 1.16.2
          kustomize: 3.4.0
          helm: 2.16.1
          helmv3: 3.0.0
          command: |
            # TODO: Currently Under development
            # We need this plugin to run conftest via helm
            echo "Installing helm-conftest plugin...."
            mkdir -p ~/.helm/plugins
            helm plugin install https://github.com/instrumenta/helm-conftest

            echo "Run conftest...."
            helm conftest helm-k8s -p test -o table
            # kustomize build helm/templates/base/kustomize | conftest test -p test -

            echo "Running heml template and kuvebal"
            helm template helm-k8s | kubeval --strict --force-color --ignore-missing-schemas

